# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='number',
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='zero', max_length=256),
        ),
    ]
